// <auto-generated />
using AvansasProject.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace AvansasProject.DAL.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
	[Migration("00000000000000_CreateIdentitySchema")]
	partial class CreateIdentityShema 
	{

	}
	
}
